import type { Metadata } from "next";
import { ChakraProvider } from "@chakra-ui/react";
import "./globals.css";
import Header from "@/components/Header";
// import Footer from "@/components/Footer";
import { AuthProvider } from "./authContext";

export const metadata: Metadata = {
  title: "CarefinderProject",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
        <ChakraProvider>
          <Header />
          {children}
          {/* <Footer /> */}
          </ChakraProvider>
          </AuthProvider>
      </body>
    </html>
  );
}